In [11]:
import numpy as np
import sys

In [33]:
a = np.array([[1, 2, 3]], dtype="int8")
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

#print matrix
print(a)

# get dimension
print("Dimension: ", a.ndim)

# get type/size
print("Type: ", b.dtype, "Size: ", b.itemsize, "bytes")

[[1 2 3]]
Dimension:  2
Type:  float64  Size:  8 bytes


## The Basics

In [22]:
a = np.array([[1,2,3]])
print(a)

[[1 2 3]]


In [23]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [24]:
#get dimension
b.ndim

2

In [25]:
#get shape
b.shape

(2, 3)

In [26]:
#get type
a.dtype

dtype('int32')

In [27]:
#get size
a.itemsize

4

In [28]:
b.itemsize

8

In [29]:
a.dtype

dtype('int32')

### Accessing/Changing specific elements, rows, columns etc

In [42]:
x = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [43]:
# get a specific element [r,c]
x[1, 5]

13

In [44]:
# get a specific row
x[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
# get a specific column
x[:, 2]

array([ 3, 10])

In [52]:
# getting a little more fancy [startindex:endindex:stepsize]
x[0, 0:6:2]

array([1, 3, 5])

In [54]:
x[1, 1:-1:2]

array([ 9, 11, 13])

In [55]:
x[1,5] = 20
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [56]:
x[:, 2] = 5
print(x)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [57]:
x[:, 2] = [1,3]
print(x)

[[ 1  2  1  4  5  6  7]
 [ 8  9  3 11 12 20 14]]


In [59]:
y = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# get specific element (work outside in)
y[0,1,1]

4

In [61]:
y[:,1,:]

array([[3, 4],
       [7, 8]])

### Initialize Different Types of Arrays

In [64]:
# all zeros matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# all ones matrix
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [66]:
np.ones((4,2,2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [67]:
# any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [68]:
np.full((3,4,5), 7)

array([[[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]],

       [[7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7],
        [7, 7, 7, 7, 7]]])

In [73]:
# any other number (full_like)
np.full_like(x, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [76]:
# random decimal numbers
np.random.rand(3,2,3)

array([[[0.74206693, 0.85283079, 0.13483154],
        [0.26422602, 0.59589034, 0.52441354]],

       [[0.65555869, 0.15160621, 0.04999056],
        [0.75525596, 0.99293777, 0.36263931]],

       [[0.0749461 , 0.22396437, 0.48792007],
        [0.55963728, 0.82241769, 0.76174415]]])

In [79]:
np.random.random_sample(x.shape)

array([[0.28170985, 0.15109082, 0.89130281, 0.08972684, 0.39834317,
        0.1275106 , 0.48531001],
       [0.01612625, 0.69740518, 0.72810012, 0.2571582 , 0.28022878,
        0.9460503 , 0.09073572]])

In [82]:
#random integer values
np.random.randint(5, size=(3,3))

array([[3, 1, 3],
       [4, 3, 4],
       [1, 2, 0]])

In [85]:
np.random.randint(-4,8, size=(3,4))

array([[-4, -2, -3,  7],
       [-1,  6,  3,  7],
       [ 7,  4,  5,  7]])

In [86]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [93]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [102]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### Be careful when copying arrays

In [105]:
a = np.array([1,2,3])
b = a.copy()
b[0]=100
print(a,b)

[1 2 3] [100   2   3]


In [104]:
print(a)

[1 2 3]


# Mathematics

In [107]:
d = np.array([1,2,3,4])
print(d)

[1 2 3 4]


In [108]:
d + 2

array([3, 4, 5, 6])

In [109]:
d - 2

array([-1,  0,  1,  2])

In [110]:
d * 2

array([2, 4, 6, 8])

In [111]:
d / 2

array([0.5, 1. , 1.5, 2. ])

In [112]:
f = np.array([1,0,1,0])
d + f

array([2, 2, 4, 4])

In [114]:
d ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [115]:
# take the sin
np.sin(d)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [116]:
np.cos(d)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear ALgebra

In [118]:
g = np.ones((2,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]


In [119]:
h = np.full((3,2), 2)
print(h)

[[2 2]
 [2 2]
 [2 2]]


In [120]:
np.matmul(g,h)

array([[6., 6.],
       [6., 6.]])

In [121]:
np.matmul(h,g)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [122]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [124]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
np.min(stats)

1

In [128]:
np.min(stats, axis=1)

array([1, 4])

In [129]:
np.max(stats)

6

In [130]:
np.max(stats, axis=0)

array([4, 5, 6])

In [131]:
np.max(stats, axis=1)

array([3, 6])

In [132]:
np.sum(stats)

21

# Reorganizing arrays

In [133]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [134]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [135]:
afterr = before.reshape(2,2,2)
print(afterr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [136]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])